name: Vault
version: 2.3.0
description: A PR-friendly version of Vault; Where PRs are actually accepted.
authors: [cereal, Sleaker, mung3r, creatorfromhell]
website: https://tnemc.net
api-version: 1.13
folia-supported: true

main: net.milkbowl.vault.Vault
load: STARTUP

commands:
  vault-info:
    description: Displays information about VaultUnlocked
    usage: |
           /<command> - Displays VaultUnlocked information
    permission: vault.admin
  vault-convert:
    description: Converts all data in economy1 and dumps it into economy2
    usage: |
           /<command> [economy1] [economy2]
    permission: vault.admin
permissions:
  vault.admin:
    description: Notifies the player when VaultUnlocked is in need of an update.
    default: op